"""New Migration

Revision ID: 1fba93448ddb
Revises: 860b53f88f4a
Create Date: 2024-05-23 07:18:12.949864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fba93448ddb'
down_revision: Union[str, None] = '860b53f88f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('nationality', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'nationality')
    # ### end Alembic commands ###
